#!/usr/bin/env bash
# A script that displays the content of /etc/passwd in a particular format

while IFS=: read -r user pass uid gid desc home shell; do
    printf "$user:$uid:$home\n"
done < /etc/passwd
