#!/bin/bash

awk '
{
    # Match and extract IP address and HTTP status code from each line
    match($0, /^([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+).* ([0-9]{3})/, arr)
    if (arr[1] && arr[2]) {
        # Print IP and HTTP status code in the desired format
        print arr[1], arr[2]
    }
}
' apache-access.log
